version: '3.7'

services:
  web:
    build: .
    command: python3.8 /books/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/books
    ports:
      - 8000:8000
    depends_on:
      - db

  db: 
    image: postgres:11
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust